In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.sample(5)

    age  gender  fever   cough       city has_covid
93   27    Male  100.0    Mild    Kolkata       Yes
19   42  Female    NaN  Strong  Bangalore       Yes
98    5  Female   98.0  Strong     Mumbai        No
32   34  Female  101.0  Strong      Delhi       Yes
51   11  Female  100.0  Strong    Kolkata       Yes

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [8]:
X_train.shape

(80, 5)

In [9]:
X_test.shape

(20, 5)

In [10]:
##AAM ZINDAGI

In [11]:
# adding simple imputer to fever column due to missing columnds
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [12]:
#OrdinalEncoding -> Cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [15]:
##OneHotEncoder -> gender, city
ohe = OneHotEncoder(drop='first', sparse_output=False)
##changes aree there from sirs lecture to the code
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also for the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [17]:
# Extracting age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

#also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [22]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

# also for the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [24]:
## Mentos Zindagi

In [26]:
from sklearn.compose import ColumnTransformer

In [28]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [29]:
transformer.fit_transform(X_train).shape

(80, 7)

In [31]:
transformer.transform(X_test).shape

(20, 7)